logLevel: INFO
deniedItems: [BUCKET, WATER_BUCKET, LAVA_BUCKET, FLINT_AND_STEEL] # usage cancelled if target block is in a denied region
protectFire: true
options:
    no-locks: LockCreateCancel
version: @VERSION@