logLevel: INFO
messages:
    regionName:
        +hasAccess: '§2%1$s§r' # 1 = Region Name
        +noAccess: '§e%1$s§r' # 1 = Region Name
        +delimiter: ', '
    denied: '-> Region §caccess denied§r: %2$s' # 2 = Formatted Region Names
    currentHasAccess: '-> §2Current regions§r: %2$s §8(%3$d)' # 2 = Formatted Region Names, 3 = Count
    currentNoAccess: '-> §eCurrent regions§r: %2$s §8(%3$d)' # 2 = Formatted Region Names, 3 = Count
    targetHasAccess: '-> §2Target regions§r: %2$s §8(%3$d at x:%4$d y:%5$d z:%6$d)' # 2 = Formatted Region Names, 3 = Count, 4 = X, 5 = Y, 6 = Z
    targetNoAccess: '-> §eTarget regions§r: %2$s §8(%3$d at x:%4$d y:%5$d z:%6$d)' # 2 = Formatted Region Names, 3 = Count, 4 = X, 5 = Y, 6 = Z
    enterHasAccess: '-> §2%2$s' # 2 = Enter Message
    enterNoAccess: '-> §e%2$s' # 2 = Enter Message
    exit: '-> §2%2$s' # 2 = Exit Message
    accessGrantAlready: '-> Region access §ealready contains§r %2$s for %3$s in %4$s' # 2 = <Access>, 3 = Region, 4 = World
    accessGrantSuccess: '-> Region §2access added§r to %2$s for %3$s in %4$s' # 2 = <Access>, 3 = Region, 4 = World
    accessGrantNotify: '§8%1$tH:%1$tM:%1$tS§r -> Region §2access granted§r to you by %2$s for %3$s in %4$s' # 2 = Grantor, 3 = Region, 4 = World
    accessReset: '-> Region §2access reset§r to %2$s for %3$s in %4$s' # 2 = <Access>, 3 = Region, 4 = World
    accessRevokeMissing: '-> Region access does §enot explicitly grant access§r to %2$s for %3$s in %4$s' # 2 = <Access>, 3 = Region, 4 = World
    accessRevokeSuccess: '-> Region §2access revoked§r from %2$s for %3$s in %4$s' # 2 = <Access>, 3 = Region, 4 = World
    ownerGrantAlready: '-> Region owners §ealready contains§r %2$s for %3$s in %4$s' # 2 = <Owner>, 3 = Region, 4 = World
    ownerGrantSuccess: '-> Region §2ownership added§r to %2$s for %3$s in %4$s' # 2 = <Owner>, 3 = Region, 4 = World
    ownerGrantNotify: '§8%1$tH:%1$tM:%1$tS§r -> Region §2ownership granted§r to you by %2$s for %3$s in %4$s' # 2 = Grantor, 3 = Region, 4 = World
    ownerReset: '-> Region §2owners reset§r to %2$s for %3$s in %4$s' # 2 = <Owner>, 3 = Region, 4 = World
    ownerRevokePrevent: '-> You can §cnot remove yourself§r as a region owner'
    ownerRevokeMissing: '-> Region owners §edoes not explicitly contain§r %2$s for %3$s in %4$s' # 2 = <Owner>, 3 = Region, 4 = World
    ownerRevokeSuccess: '-> Region §2ownership revoked§r from %2$s for %3$s in %4$s' # 2 = <Owner>, 3 = Region, 4 = World
    activated: '-> §2Activated§r region %2$s in %3$s' # 2 = Region, 3 = World
    deactivated: '-> §eDeactivated§r region %2$s in %3$s' # 2 = Region, 3 = World
    deleted: '-> §2Region deleted§r: %2$s in %3$s' # 2 = Region, 3 = World
    set: '-> §2Set working region§r to: %2$s in %3$s' # 2 = Region, 3 = World
    unset: '-> §2Unset working region'
    reload: '-> SimpleRegions configuration §2reloaded'
    requiresParameter: '-> Required §cparameter missing§r: %2$s' # 2 = Parameter
    requiresOwner: '-> Command cancelled when §cnot region owner§r: %2$s' # 2 = Owner
    requiresPlayer: '-> Command cancelled when §cnot in-game player'
    regionNotFound: '-> Region §enot found'
    worldNotFound: '-> World §enot found' # 2 = World
    regionCreated: '-> §2Region created§r: %2$s in %3$s' # 2 = Region, 3 = World
    blockNotIdentifed: '-> Target block §enot identified'
    coordinateNotIdentified: '-> Coordinate type %2$s §enot recognized' # 2 = Type
    coordinateUpdated: '-> Region §2coordinates updated'
    unsupportedParameter: '-> §eUnsupported parameter§r: %2$s §8(%3$s)' # 2 = Parameter, 3 = Reason
    enterPrevious: '-> Previous region enter format: %2$s' # 2 = Enter Format
    enterSet: '-> Region §2enter format set'
    enterExisting: '-> Region enter format: %2$s' # 2 = Enter Format
    enterMessage: '-> Region enter message: %2$s' # 2 = Formatted Enter Message
    exitPrevious: '-> Previous region exit format: %2$s'
    exitSet: '-> Region §2exit format set'
    exitExisting: '-> Region exit format: %2$s' # 2 = Exit Format
    exitMessage: '-> Region exit message: %2$s' # 2 = Formatted Exit Message
    undefined: '-> §eUndefined region§r; To define: /define'
    inactive: '-> §eInactive region§r; To activate: /region_on'
    area: '-> Area: %2$sx * %3$sz = %4$s blocks squared' # 2 = X Length, 3 = Z Length, 4 = Area
    volume: '-> Volume: %2$sx * %3$sy * %4$sz = %5$s blocks cubed' # 2 = X Length, 3 = Y Length, 4 = Z Length, 5 = Volume
    describe: # 2 = Region, 3 = World, 4 = Active, 5 = Owners, 6 = Access, 7 = North, 8 = East, 9 = South, 10 = West, 11 = Down, 12 = Up 
        - '-> -- Region: %2$s in %3$s'
        - '-> Active: %4$s'
        - '-> Owners: %5$s'
        - '-> Access: %6$s'
        - '-> x:  [West] %10$d  to  %8$d [East]'
        - '-> y:  [North] %7$d  to  %9$d [South]'
        - '-> z:  [Down] %11$d  to  %12$d [Up]'
    describeDefault: # 2 = Region, 3 = World, 4 = Active, 5 = Owners, 6 = Access, 7 = North, 8 = East, 9 = South, 10 = West, 11 = Down, 12 = Up
        - '-> -- Region: %2$s in %3$s'
        - '-> Active: %4$s'
        - '-> Access: %6$s'
version: @VERSION@