name: SimpleRegions
version: @VERSION@
description: Protect regions of blocks so only configured players can modify
author: EdGruberman (ed@rjump.com)
website: http://github.com/EdGruberman/SimpleRegions
main: edgruberman.bukkit.simpleregions.Main
commands:
    'simpleregions:current':
        aliases: [region.current, region]
        description: Show your current region
        permission: simpleregions.current
        usage: '§f-> §7Usage: §b/<command>'
    'simpleregions:target':
        aliases: [region.target]
        description: Show region where you are looking
        permission: simpleregions.target
        usage: '§f-> §7Usage: §b/<command>'
    'simpleregions:context':
        aliases: [region.context]
        description: Set your working region
        permission: simpleregions.context
        usage: '§f-> §7Usage: §b/<command> §o<Region>§3[ §b§o<World>§3]'
    'simpleregions:clear':
        aliases: [region.clear]
        description: Unset your working region
        permission: simpleregions.clear
        usage: '§f-> §7Usage: §b/<command>'
    'simpleregions:describe':
        aliases: [region.describe]
        description: Show region description
        permission: simpleregions.describe
        usage: '§f-> §7Usage: §b/<command>§3[ §b§o<Region>§3[ §b§o<World>§3]]'
    'simpleregions:activate':
        aliases: [region.activate]
        description: Enable region protection * Requires owner
        permission: simpleregions.activate
        usage: '§f-> §7Usage: §b/<command>§3[ §b§o<Region>§3[ §b§o<World>§3]]'
    'simpleregions:deactivate':
        aliases: [region.deactivate]
        description: Disable region protection * Requires owner
        permission: simpleregions.deactivate
        usage: '§f-> §7Usage: §b/<command>§3[ §b§o<Region>§3[ §b§o<World>§3]]'
    'simpleregions:promote':
        aliases: [region.promote]
        description: Add explicit region owner * Requires owner
        permission: simpleregions.promote
        usage: '§f-> §7Usage: §b/<command> §o<Owner>§3[ §b§o<Region>§3[ §b§o<World>§3]]'
    'simpleregions:demote':
        aliases: [region.demote]
        description: Remove explicit region owner * Requires owner
        permission: simpleregions.owners.revoke
        usage: '§f-> §7Usage: §b/<command> §o<Owner>§3[ §b§o<Region>§3[ §b§o<World>§3]]'
    'simpleregions:reform':
        aliases: [region.reform]
        description: Reset explicit region owners * Requires owner
        permission: simpleregions.owners.reset
        usage: '§f-> §7Usage: §b/<command> §o<Owner>§3[ §b§o<Region>§3[ §b§o<World>§3]]'
    'simpleregions:grant':
        aliases: [region.grant]
        description: Add explicit region access * Requires owner
        permission: simpleregions.grant
        usage: '§f-> §7Usage: §b/<command> §o<Access>§3[ §b§o<Region>§3[ §b§o<World>§3]]'
    'simpleregions:revoke':
        aliases: [region.revoke]
        description: Remove explicit region access * Requires owner
        permission: simpleregions.revoke
        usage: '§f-> §7Usage: §b/<command> §o<Access>§3[ §b§o<Region>§3[ §b§o<World>§3]]'
    'simpleregions:replace':
        aliases: [region.replace]
        description: Reset explicit region access * Requires owner
        permission: simpleregions.replace
        usage: '§f-> §7Usage: §b/<command> §o<Access>§3[ §b§o<Region>§3[ §b§o<World>§3]]'
    'simpleregions:greeting':
        aliases: [region.greeting]
        description: View/set region enter message format * Requires owner
        permission: simpleregions.greeting
        usage: '§f-> §7Usage: §b/<command>§3[ (§b§o<Message>§3|§bdefault§3)]'
    'simpleregions:farewell':
        aliases: [region.farewell]
        description: View/set region exit message format * Requires owner
        permission: simpleregions.farewell
        usage: '§f-> §7Usage: §b/<command>§3[ (§b§o<Message>§3|§bdefault§3)]'
    'simpleregions:create':
        aliases: [region.create]
        description: Create new region
        permission: simpleregions.create
        usage: '§f-> §7Usage: §b/<command> §o<Region>§3[ §b§o<World>§3]'
    'simpleregions:define':
        aliases: [region.define]
        description: Define working region coordinates
        permission: simpleregions.define
        usage: '§f-> §7Usage: §b/<command>§3[ (§b1§3|§b2§3)|((§bn§3|§be§3|§bs§3|§bw§3|§bu§3|§bd§3)[§b:§o<Coordinate>§3])[ §b§o<Region>§3[ §b§o<World>§3]]]'
    'simpleregions:delete':
        aliases: [region.delete]
        description: Delete region
        permission: simpleregions.delete
        usage: '§f-> §7Usage: §b/<command> §o<Region> <World>'
    'simpleregions:rename':
        aliases: [region.rename]
        description: Rename region
        permission: simpleregions.rename
        usage: '§f-> §7Usage: §b/<command> §o<New>§3[ §b§o<Region>§3[ §b§o<World>§3]]'
    'simpleregions:attach':
        aliases: [region.attach]
        description: Add option to region
        permission: simpleregions.option.add
        usage: '§f-> §7Usage: §b/<command> §o<Option>§3[ §b§o<Region>§3[ §b§o<World>§3]]'
    'simpleregions:detach':
        aliases: [region.detach]
        description: Remove option from region
        permission: simpleregions.option.remove
        usage: '§f-> §7Usage: §b/<command> §o<Option>§3[ §b§o<Region>§3[ §b§o<World>§3]]'
    'simpleregions:reload':
        description: Reload configuration
        permission: simpleregions.reload
        usage: '§f-> §7Usage: §b/<command>'
permissions:
    'simpleregions.[players]':
        description: All players; "Permission group" used to grant access to regions
        default: true
    simpleregions.admin:
        description: Can use all features
        default: op
        children:
            simpleregions.designer: true
            simpleregions.override: true
            simpleregions.reload: true
    simpleregions.user:
        description: Can use basic features
        default: true
        children:
            simpleregions.current: true
            simpleregions.target: true
            simpleregions.context: true
            simpleregions.clear: true
            simpleregions.describe: true
            simpleregions.grant: true
            simpleregions.revoke: true
            simpleregions.replace: true
            simpleregions.promote: true
            simpleregions.demote: true
            simpleregions.reform: true
            simpleregions.activate: true
            simpleregions.deactivate: true
    simpleregions.designer:
        description: Can create and edit regions
        default: false
        children:
            simpleregions.override.commands: true
            simpleregions.greeting: true
            simpleregions.farewell: true
            simpleregions.create: true
            simpleregions.define: true
            simpleregions.delete: true
            simpleregions.rename: true
            simpleregions.option.add: true
            simpleregions.option.remove: true
            simpleregions.message.color: true
    simpleregions.override:
        description: Can interact with regions as owner
        default: false
        children:
            simpleregions.override.commands: true
            simpleregions.override.protection: true
    simpleregions.override.commands:
        description: Can use region commands even if not owner
        default: false
    simpleregions.override.protection:
        description: Can interact with regions in-game even if not owner
        default: false
    simpleregions.current:
        description: Can use current command
        default: false
    simpleregions.target:
        description: Can use target command
        default: false
    simpleregions.context:
        description: Can use context command
        default: false
    simpleregions.clear:
        description: Can use clear command
        default: false
    simpleregions.describe:
        description: Can use describe command
        default: false
    simpleregions.activate:
        description: Can use activate command * Requires owner
        default: false
    simpleregions.deactivate:
        description: Can use deactivate command * Requires owner
        default: false
    simpleregions.grant:
        description: Can use grant command * Requires owner
        default: false
    simpleregions.revoke:
        description: Can use revoke command * Requires owner
        default: false
    simpleregions.replace:
        description: Can use replace command * Requires owner
        default: false
    simpleregions.promote:
        description: Can use promote command * Requires owner
        default: false
    simpleregions.demote:
        description: Can use demote command * Requires owner
        default: false
    simpleregions.reform:
        description: Can use reform command * Requires owner
        default: false
    simpleregions.greeting:
        description: Can use greeting command
        default: false
    simpleregions.farewell:
        description: Can use farewell command
        default: false
    simpleregions.create:
        description: Can use create command
        default: false
    simpleregions.define:
        description: Can use define command
        default: false
    simpleregions.delete:
        description: Can use delete command
        default: false
    simpleregions.rename:
        description: Can use rename command
        default: false
    simpleregions.attach:
        description: Can use attach command
        default: false
    simpleregions.detach:
        description: Can use detach command
        default: false
    simpleregions.reload:
        description: Can use reload command
        default: false
    simpleregions.message.color:
        description: Can use color codes in greetings and farewells
        default: false