name: @NAME@
description: Protect regions of the map so only selected players can edit them.
depend: [MessageManager]
version: @VERSION@
author: @AUTHOR@
main: @MAIN@
commands:
    region:
        description: Describe, modify, create, and remove regions.
        permission: simpleregions.region
        usage: |
            /<command> - Show your current region(s).
            /<command> info - Show region details.
            /<command> (+|-|=)[access] <Player> - Add/remove access.
            /<command> (+|-|=)owner <Player> - Add/remove owners.
            /<command> (+|-)active - Set region status.
            /<command> <Region> <Action> - Remote management.
permissions:
    simpleregions.region.read:
        description: Can use all read related actions of region command.
        default: true
        children:
            simpleregions.region.current: true
            simpleregions.region.target: true
            simpleregions.region.set: true
            simpleregions.region.detail: true
            simpleregions.region.size: true
    simpleregions.region.current:
        description: Can use current action of region command.
        default: false
        children:
            simpleregions.region: true
    simpleregions.region.target:
        description: Can use target action of region command.
        default: false
        children:
            simpleregions.region: true
    simpleregions.region.set:
        description: Can use set and unset actions of region command.
        default: false
        children:
            simpleregions.region: true
    simpleregions.region.detail:
        description: Can use detail action of region command.
        default: false
        children:
            simpleregions.region: true
    simpleregions.region.size:
        description: Can use detail action of region command.
        default: false
        children:
            simpleregions.region: true
    simpleregions.region.active:
        description: Can use the active action of region command.
        default: op
        children:
            simpleregions.region: true
    simpleregions.region.access:
        description: Can use access action of region command.
        default: op
        children:
            simpleregions.region: true
    simpleregions.region.owner:
        description: Can use owner action of region command.
        default: op
        children:
            simpleregions.region: true
    simpleregions.region.message:
        description: Can use enter and exit actions of region command.
        default: op
        children:
            simpleregions.region: true
    simpleregions.region.create:
        description: Can use create action of region command.
        default: op
        children:
            simpleregions.region: true
    simpleregions.region.define:
        description: Can use define action of region command.
        default: op
        children:
            simpleregions.region: true
    simpleregions.region.delete:
        description: Can use delete action of region command.
        default: op
        children:
            simpleregions.region: true
    simpleregions.region.reload:
        description: Can use reload action of region command.
        default: op
        children:
            simpleregions.region: true
    simpleregions.region:
        description: Can use region command.
        default: false