name: SimpleRegions
description: Protect regions of the map so only selected players can edit them.
version: %VERSION%
depend: [MessageManager, SimpleSecurity]
main: edgruberman.bukkit.simpleregions.Main
author: EdGruberman (ed@rjump.com)
commands:
    region:
        description: Describe, modify, create, and remove regions.
        usage: |
            /<command> - Show your current region(s).
            /<command> info - Show region details.
            /<command> (+|-)active - Set region status.
            /<command> (+|-)owner <Player> - Add/remove owners.
            /<command> (+|-)helper <Player> - Add/remove helpers.
            /<command> <Region>[ <Action>] - Remote management.
